name: openvpn_flutter_example
description: Demonstrates how to use the openvpn_flutter plugin. 
publish_to: 'none' 

environment:
  sdk: ">=2.15.0 <4.0.0" 
dependencies:
  flutter:
    sdk: flutter

  openvpn_flutter: ^1.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^1.0.0
 
flutter: 
  uses-material-design: true 